### ISSUE TITLE
not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by baoxingsong** [ablab/quast#105]
Hi, I have the following error message using the command 
```quast.py canu.fa flye.fa necat.fa wtdbg24.fa.fa wtdbg21.fa -r Sorghum_bicolor.Sorghum_bicolor_NCBIv3.dna.toplevel.fa -g Sorghum_bicolor.Sorghum_bicolor_NCBIv3.42.gff3 -t 112 --large -k --upper-bound-assembly --circos --nanopore reads.fastq```

```
2019-06-23 09:31:30
Generating Upper Bound Assembly...
  Pre-processing reads...
  Running BWA for reference...
  Done.
  Sorting SAM-file for reference...
  Calculating reads coverage...
  Running repeat masking tool...

'>' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/bs674/anaconda3/envs/quast/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg-info/scripts/quast.py", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/home/bs674/anaconda3/envs/quast/lib/python3.6/site-packages/quast-5.0.2-py3.6.egg-info/scripts/quast.py", line 95, in main
    os.path.join(output_dirpath, qconfig.optimal_assembly_basename))
  File "/home/bs674/anaconda3/envs/quast/lib/python3.6/site-packages/quast_libs/optimal_assembly.py", line 476, in do
    unique_covered_regions, repeats_regions = get_unique_covered_regions(ref_fpath, tmp_dir, log_fpath, binary_fpath, insert_size, uncovered_fpath, use_long_reads=long_reads)
  File "/home/bs674/anaconda3/envs/quast/lib/python3.6/site-packages/quast_libs/optimal_assembly.py", line 394, in get_unique_covered_regions
    filtered_repeats_fpath, repeats_regions = check_repeats_instances(coords_fpath, long_repeats_fpath, use_long_reads)
  File "/home/bs674/anaconda3/envs/quast/lib/python3.6/site-packages/quast_libs/optimal_assembly.py", line 304, in check_repeats_instances
    if matched_bases > qconfig.optimal_assembly_insert_size:
TypeError: '>' not supported between instances of 'int' and 'str'
ERROR! exception caught!
```

Is there an update fixed this problem, please?

**Comment by Ritu-Kundu** [comment]
Hi,

I am facing the same issue. I tried changing the script optimal_assembly.py (`if matched_bases > int(qconfig.optimal_assembly_insert_size)`) but then it runs into another error. Is there any resolution?

**Comment by lovishpuri** [comment]
The default value of optimal_assembly_insert_size in /quast_libs/qconfig.py is set to 'auto'. In the function check_repeats_instances thi value was not being checked which results in  error.
This should be fixed by https://github.com/ablab/quast/pull/172

Please note that you can set your own values for optimal_assembly_insert_size in qconfig.py (/quast_libs/qconfig.py )
