### ISSUE TITLE
Error while creating circos plot

### ISSUE THREAD

**Issue by mariosagb** [ablab/quast#114]
Dear developers,

After the following step: 
```
Creating large visual summaries...
This may take a while: press Ctrl-C to skip this step..
1 of 3: Creating Icarus viewers...
2 of 3: Creating Circos plot...
```

Quast throws an error and exits:
```
list index out of range
Traceback (most recent call last):
File "/opt/quast-5.0.2/quast.py", line 307, in <module>
return_code = main(sys.argv[1:])
File "/opt/quast-5.0.2/quast.py", line 265, in main
features_containers, cov_fpath, os.path.join(output_dirpath, 'circos'), logger)
File "/opt/quast-5.0.2/quast_libs/circos.py", line 560, in do
conf_fpath, circos_legend_fpath = create_conf(ref_fpath, contigs_fpaths, contig_report_fpath_pattern, output_dir, gc_fpath, features_containers, cov_fpath, logger)
File "/opt/quast-5.0.2/quast_libs/circos.py", line 443, in create_conf
cov_data_fpath, cov_points = create_coverage_plot(cov_fpath, window_size, chr_lengths, data_dir)
File "/opt/quast-5.0.2/quast_libs/circos.py", line 257, in create_coverage_plot
cov_by_chrom[chrom][pos // window_size].append(depth)
IndexError: list index out of range
ERROR! exception caught!
```

I can not understand the reason for this. How can I overcome this? Thank you in advance.
Kind regards,
Marios

**Comment by alexeigurevich** [comment]
Dear Marios,
The problem seems rather strange but maybe it is a bug in our code. Most likely it is somehow related to your reads and their alignment to reference genome.

However, to reproduce and fix the issue we need sample data from your side. Could you attached them here (direct upload or via a link to some other host place) or send us privately via quast.support@cab.spbu.ru?

Ideally, it should be a minimal example that still results in the error message. E.g. full reference and first 1K or 10K reads. For downsampling, you can use, e.g. [seqtk sample](https://github.com/lh3/seqtk).
However, we can work with the full dataset as well if it is more suitable for you.

**Comment by mariosagb** [comment]
This is the way we run quast:
```
python /opt/quast-5.0.2/quast.py \
-o /home/mgabriel/Downloads/data/new_refDV2/output \
-r /home/mgabriel/Downloads/data/new_refDV2/GCF_000005245.1_dvir_caf1_genomic.fna \
--features /home/mgabriel/Downloads/data/new_refDV2/GCF_000005245.1_dvir_caf1_genomic.gff \
--threads 16 \
--eukaryote \
--large \
--circos \
--conserved-genes-finding \
--gene-finding \
--rna-finding \
--fragmented \
--pe1 /home/mgabriel/Downloads/data/DroVir2/SRR1536175_1.fastq.gz \
--pe2 /home/mgabriel/Downloads/data/DroVir2/SRR1536175_2.fastq.gz \
/home/mgabriel/Downloads/data/DroVir2/flye/assembly.fasta
```
GCF_000005245.1_dvir_caf1_genomic.fna and GCF_000005245.1_dvir_caf1_genomic.gff were downloaded from ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/245/GCF_000005245.1_dvir_caf1

SRR1536175_1.fastq.gz and SRR1536175_2.fastq.gz were downloaded from https://www.ebi.ac.uk/ena/data/view/SRR1536175

assembly.fasta was produced using MaSuRCA. The format is:

```
>contig_1
ATGTTTATAATTGTGCTTATGCTTATGTGCTAAGTTATGTTAAAGGGTGGGTGCGACTAT
GGATATGTCACTCCCCCAACCATTAGAAAAGTGCCTGTCCTCAGGTGTTTAAGTTTGGAT
...
>contig_2
TTTGGTCAAGTAACAGCAGAGATAACACCGACGGCTGCGGACATCATCCAACAGCAGAAA
ATAACAATCATAATTACAGCCTAAGAGCAAATAGTTTTTTTGCGCGCTCTTTGTAAGCTG
...
```

Thank you for your quick response.

**Comment by bersbers** [comment]
Hello, I am experiencing exactly the same problem, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by bersbers** [comment]
Hello, I am experiencing exactly the same problem, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by bersbers** [comment]
Hello, I am experiencing exactly the same problem, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by bersbers** [comment]
Hello, I have been experiencing exactly the same problem since forever, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!


2020-02-26 16:59:50
Creating large visual summaries...
This may take a while: press Ctrl-C to skip this step..
  1 of 3: Creating Icarus viewers...
  2 of 3: Creating Circos plot...

list index out of range
Traceback (most recent call last):
  File "/home/calla2/quast-5.0.2/quast/lib/python2.7/site-packages/quast-5.0.2-py2.7.egg/EGG-INFO/scripts/quast.py", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/home/calla2/quast-5.0.2/quast/lib/python2.7/site-packages/quast-5.0.2-py2.7.egg/EGG-INFO/scripts/quast.py", line 265, in main
    features_containers, cov_fpath, os.path.join(output_dirpath, 'circos'), logger)
  File "/home/calla2/quast-5.0.2/quast/local/lib/python2.7/site-packages/quast-5.0.2-py2.7.egg/quast_libs/circos.py", line 560, in do
    conf_fpath, circos_legend_fpath = create_conf(ref_fpath, contigs_fpaths, contig_report_fpath_pattern, output_dir, gc_fpath, features_containers, cov_fpath, logger)
  File "/home/calla2/quast-5.0.2/quast/local/lib/python2.7/site-packages/quast-5.0.2-py2.7.egg/quast_libs/circos.py", line 443, in create_conf
    cov_data_fpath, cov_points = create_coverage_plot(cov_fpath, window_size, chr_lengths, data_dir)
  File "/home/calla2/quast-5.0.2/quast/local/lib/python2.7/site-packages/quast-5.0.2-py2.7.egg/quast_libs/circos.py", line 257, in create_coverage_plot
    cov_by_chrom[chrom][pos // window_size].append(depth)
IndexError: list index out of range
ERROR! exception caught!

**Comment by bersbers** [comment]
Hello, I have been experiencing exactly the same problem since forever, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by bersbers** [comment]
Hello, I have been experiencing exactly the same problem since forever, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by bersbers** [comment]
Hello, I have been experiencing exactly the same problem since forever, could you tell me what was the cause  and how did you solved please?. I do have circos running independently and I am sure QUAST can access it. THANK YOU!

**Comment by mariosagb** [comment]
I just installed circos (http://circos.ca/software/installation/) and then I tested if it was installed correctly. Finally, I added circos in my path and QUAST was able to run successfully.

**Comment by bersbers** [comment]
Thanks, CIRCOS is def. in my path but still ... I will keep trying ...
