### ISSUE TITLE
Cannot allocate memory even though more than enough RAM available

### ISSUE THREAD

**Issue by dpellow** [ablab/quast#138]
Hi I keep running into an error when running metaquast:
`OSError: [Errno 12] Cannot allocate memory`

The last few lines of metaquast.log are reproduced below:
```
Run QUAST on different references in parallel..

[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "metaquast.py", line 406, in <module>
    return_code = main(sys.argv[1:])
  File "metaquast.py", line 323, in main
    run_parallel(_run_quast_per_ref, parallel_run_args, qconfig.max_threads, filter_results=True)
  File "XXXX/dpellow/bin/quast-5.0.2/quast_libs/qutils.py", line 1065, in run_parallel
    results_tuples = Parallel(**parallel_args)(delayed(_fn)(*args) for args in fn_args)
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.11-py2.7.egg/joblib/parallel.py", line 749, in __call__
    n_jobs = self._initialize_backend()
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.11-py2.7.egg/joblib/parallel.py", line 547, in _initialize_backend
    **self._backend_args)
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.11-py2.7.egg/joblib/_parallel_backends.py", line 317, in configure
    self._pool = MemmapingPool(n_jobs, **backend_args)
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.11-py2.7.egg/joblib/pool.py", line 600, in __init__
    super(MemmapingPool, self).__init__(**poolargs)
  File "/usr/local/lib/python2.7/dist-packages/joblib-0.11-py2.7.egg/joblib/pool.py", line 420, in __init__
    super(PicklingPool, self).__init__(**poolargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

and the last few lines of quast.log:
```
2020-04-16 15:52:33
RESULTS:
  Text versions of total report are saved to XXXXXX/quast_out/combined_reference/report.txt, report.tsv, and report.tex
  Text versions of transposed total report are saved to XXXXXX/quast_out/combined_reference/transposed_report.txt, transposed_report.tsv, and transposed_report.tex
  HTML version (interactive tables and plots) is saved to XXXXXX/quast_out/combined_reference/report.html
  PDF version (tables and plots) is saved to /XXXXXX/quast_out/combined_reference/report.pdf
```

**Comment by hitengwen** [comment]
Hi, dpellow. I have came up with the same err message. Have you soved the problem?

**Comment by dpellow** [comment]
I don't remember that I did something to solve it, but I haven't run into the problem again.

**Comment by alexeigurevich** [comment]
Hi @hitengwen, 
You can try to run with `--memory-efficient` or just in a single thread to reduce memory consumption. However, it is possible that your RAM is not enough to process a large assembly/reference if this is the case.

**Comment by Praseedas** [comment]
I have been running quast for 2 days but I am getting error during minimap2 stage of contigs alignment. My RAM is 31 GB only, and my assemble file is 2Gb in size and  my ref genome i also around 1.8gb. So n this case what should i do?
