### ISSUE TITLE
ImportError: No module named joblib2 ERROR! exception caught!

### ISSUE THREAD

**Issue by Luyang-1987** [ablab/quast#141]
when i ran the quast, i got the ImportError,
here is my code
`quast -o quast_B_cep_out -R reference_genome/BCep_ref.fna -G reference_genome/BCep_ref.gff -l spades_default, spades_kmers_careful, megahit_default, megahit_min_count_3 -t 4 -m 1000 spades_default_assembly/contigs.fasta spades_kmers_set_careful_assembly/contigs.fasta megahit_default_assembly/final.contigs.fa megahit_min_count_3_assembly/final.contigs.fa
`

**Comment by alexeigurevich** [comment]
Could you please specify which quast versions are you using and how it was installed (e.g. from .tar.gz package, using bioconda, using pip, etc)?

In any case, most probably installing `joblib` Python library will solve the issue (e.g. `pip install joblib`)

**Comment by Luyang-1987** [comment]
i used bioconda to install the quast, Version: 5.0.2, b7350347c, 
and i installed the joblib using pip to install the joblib, and try my code again, but it got the same issue

**Comment by JNdurubing** [comment]
> i used bioconda to install the quast, Version: 5.0.2, b7350347c,
> and i installed the joblib using pip to install the joblib, and try my code again, but it got the same issue

I also have the same question about quast.

**Comment by mrmrwinter** [comment]
Hi, Im having this issue but when running standalone QUAST.

I receive the joblib3 error, but this is the result of a traced back error where it cannot find joblib for python 3, goes to an exception to look for joblib2 and 3 in python 2, then throws the error.

Traceback (most recent call last):
File "/home/531734/.conda/envs/quast/bin/quast", line 307, in <module>
return_code = main(sys.argv[1:])
File "/home/531734/.conda/envs/quast/bin/quast", line 107, in main
contigs_fpaths, old_contigs_fpaths = qutils.correct_contigs(contigs_fpaths, corrected_dirpath, labels, reporting)
File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 180, in correct_contigs
old_fpaths, corr_fpaths, broken_scaffold_fpaths, logs, is_fatal_error = run_parallel(parallel_correct_contigs, parallel_run_args, n_jobs)
File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 1064, in run_parallel
from joblib3 import Parallel, delayed
`ModuleNotFoundError: No module named 'joblib3'``

Strangely, when i run quast in my environment locally it works, when i run it as a batch job, calling the same environment, it hits the error.

Has anyone managed to fix this?
