### ISSUE TITLE
SyntaxError during setup.py

### ISSUE THREAD

**Issue by tbaker18** [ablab/quast#155]
Greetings,

I have been trying to install your software, but I keep running into a SyntaxError after calling ./setup.py install or install_full. I have python2.7 and python3.6.3 along with all other dependencies installed on my linux distro. I have attached the console output just before the traceback error occurs. I searched through your issue history and it does not seem like this has been a problem before so I can't really pinpoint whether the problem is my version of python or if its a bug in the code.

```
Installed /usr/local/lib/python2.7/dist-packages/quast-5.0.2-py2.7.egg
Processing dependencies for quast==5.0.2
Searching for joblib
Reading https://pypi.python.org/simple/joblib/
Best match: joblib 0.17.0
Downloading https://files.pythonhosted.org/packages/ef/e9/80bdaef3848e8aa5e518f516bdfb79cc5d81c57ead939c541c20eecd7633/joblib-0.17.0.tar.gz#sha256=9e284edd6be6b71883a63c9b7f124738a3c16195513ad940eae7e3438de885d5
Processing joblib-0.17.0.tar.gz
Writing /tmp/easy_install-MxG_Xm/joblib-0.17.0/setup.cfg
Running joblib-0.17.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MxG_Xm/joblib-0.17.0/egg-dist-tmp-kDxz5w
```

```
Traceback (most recent call last):
  File "./setup.py", line 268, in <module>
    script_args=args,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-hZn54t/joblib-0.17.0/setup.py", line 6, in <module>
    # All Rights Reserved
  File "/tmp/easy_install-hZn54t/joblib-0.17.0/joblib/__init__.py", line 113, in <module>
  File "/tmp/easy_install-hZn54t/joblib-0.17.0/joblib/memory.py", line 274
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax
```

Thanks,
Tim

**Comment by tbaker18** [comment]
Greetings again,

I looked into issue #152 and it seems like I have the same problem. I re-ran the setup with the path to the conda python and it was successful. I'll close this issue.
