### ISSUE TITLE
AttributeError: module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by XMTian** [ablab/quast#157]
Hi,

When I run quast, I got this error. Could you help me to figure it out?

`/usr/local/bin/quast -t 2 -o ASSEMBLY/QUAST_out -m 500 ASSEMBLY/final_assembly.fasta

Version: 5.0.2, 0bb1dd1b

System information:
  OS: macOS-10.13.6-x86_64-i386-64bit (macosx)
  Python version: 3.9.1
  CPUs number: 24

Started: 2021-01-15 13:50:49

Logging to /Users/xmtian/test/ASSEMBLY/QUAST_out/quast.log

CWD: /Users/xmtian/test
Main parameters: 
  MODE: default, threads: 2, minimum contig length: 500, minimum alignment length: 65, \
  ambiguity: one, threshold for extensive misassembly size: 1000

Contigs:
  Pre-processing...
  ASSEMBLY/final_assembly.fasta ==> final_assembly

module 'cgi' has no attribute 'escape'
Traceback (most recent call last):
  File "/usr/local/bin/quast", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/usr/local/bin/quast", line 148, in main
    from quast_libs import basic_stats
  File "/usr/local/Cellar/quast/5.0.2/quast_libs/basic_stats.py", line 15, in <module>
    from quast_libs.circos import set_window_size
  File "/usr/local/Cellar/quast/5.0.2/quast_libs/circos.py", line 25, in <module>
    from quast_libs.icarus_utils import get_assemblies, check_misassembled_blocks, Alignment
  File "/usr/local/Cellar/quast/5.0.2/quast_libs/icarus_utils.py", line 15, in <module>
    from quast_libs.html_saver.html_saver import trim_ref_name
  File "/usr/local/Cellar/quast/5.0.2/quast_libs/html_saver/html_saver.py", line 18, in <module>
    from quast_libs.site_packages.jsontemplate import jsontemplate
  File "/usr/local/Cellar/quast/5.0.2/quast_libs/site_packages/jsontemplate/jsontemplate.py", line 583, in <module>
    'html': cgi.escape,
AttributeError: module 'cgi' has no attribute 'escape'`

Thanks in advance!

**Comment by zwets** [comment]
See PR #129. This is supposedly fixed in 5.1.0rc1. You can work around it by replacing `cgi.escape` by `html.escape`, and `import cgi` by `import html` in `quast_libs/site_packages/jsontemplate/jsontemplate.py`.

**Comment by XMTian** [comment]
Thank you for your prompt reply! I have solved that!

**Comment by shamshad1987** [comment]
Hi Zwets, 
I had the same issue and I replaced  cgi.escape by html.escape, and import cgi by import html in quast_libs/site_packages/jsontemplate/jsontemplate.py. But now I am having a different issue which is "name 'cgi' is not defined". 
Can you please help. I am using the latest version of quast.
Thanks
Shamshad 

Here is a snapshot.

Version: 5.0.2

System information:
  OS: Linux-5.4.0-60-generic-x86_64-with-glibc2.10 (linux_64)
  Python version: 3.8.5
  CPUs number: 32

Started: 2021-04-01 06:53:12

Logging to /mnt/quast/quast/quast.log

CWD: /mnt/quast
Main parameters:
  MODE: default, threads: 32, eukaryotic: true, split scaffolds: true, minimum contig length: 500, \
  minimum alignment length: 65, ambiguity: one, threshold for extensive misassembly size: 1000

Contigs:
  Pre-processing...
  xyz.fasta ==>xyz
    breaking scaffolds into contigs:
      52108 scaffolds (xyz) were broken into 171822 contigs (xyz_broken)

name 'cgi' is not defined
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/EGG-INFO/scripts/quast.py", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/EGG-INFO/scripts/quast.py", line 148, in main
    from quast_libs import basic_stats
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/basic_stats.py", line 15, in <module>
    from quast_libs.circos import set_window_size
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/circos.py", line 25, in <module>
    from quast_libs.icarus_utils import get_assemblies, check_misassembled_blocks, Alignment
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/icarus_utils.py", line 15, in <module>
    from quast_libs.html_saver.html_saver import trim_ref_name
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/html_saver/html_saver.py", line 18, in <module>
    from quast_libs.site_packages.jsontemplate import jsontemplate
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/site_packages/jsontemplate/jsontemplate.py", line 583, in <module>
    'html': cgi.escape,
NameError: name 'cgi' is not defined
ERROR! exception caught!

**Comment by alexeigurevich** [comment]
Hi @shamshad1987 ,
This means that you have not changed the file properly and 'cgi' is still in `/home/ubuntu/anaconda3/lib/python3.8/site-packages/quast-5.0.2-py3.8.egg/quast_libs/site_packages/jsontemplate/jsontemplate.py`. Please double check that all occurrences or `cgi` in this file are replaced with `html` (specifically on line 583).
Or you can try [v.5.1.0rc1](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) where this issue is fixed.

**Comment by rlorigro** [comment]
Any reason why this is not in the latest release?

**Comment by alexeigurevich** [comment]
Hi @rlorigro, this _is_ in the latest release which is [v.5.1.0rc1](https://github.com/ablab/quast/releases/tag/quast_5.1.0rc1) now. The issue is that this is a release candidate and we didn't add it to conda. We plan to do this with the stable 5.1.0 but we are rather slow with transforming v.5.1.0rc1 into mature 5.1.0. This is because Quast is not the primary project for all key developers, so we work on it only in the spare time. Still, the project is not abandoned!
Sorry for the inconvenience.

**Comment by rlorigro** [comment]
Hmm maybe I was confused but I thought I used the latest release to run quast on Ubuntu 20.04 the day I made that comment. I had to remove it and rebuild form master to avoid this 'escape' module error.
