### ISSUE TITLE
unknown error while running QUAST on mac

### ISSUE THREAD

**Issue by Rajmandage22** [ablab/quast#191]
I am trying to run QUAST on Mac OS with QUAST quast-5.1.0rc1 version. 

2021-11-11 12:41:07
Running Reads analyzer...

NOTICE: Improper read names in genome1.fasta.gz (forward reads)! Names should end with /1 (for forward reads) or /2 (for reverse reads) but @NS500335:165:H5HVHBGXB:1:11101:16989:1058 was found!
QUAST will attempt to fix read names.

NOTICE: Improper read names in genome2.fasta.gz (reverse reads)! Names should end with /1 (for forward reads) or /2 (for reverse reads) but @NS500335:165:H5HVHBGXB:1:11101:16989:1058 was found!
QUAST will attempt to fix read names.
  Logging to files SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_spades_assembly_output_9_Nov_2021/reads_stats/reads_stats.log and SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_spades_assembly_output_9_Nov_2021/reads_stats/reads_stats.err...
  Will not calculate coverage (--fast or --no-html, or --no-icarus, or --space-efficient is specified)
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.8/site-packages/joblib/pool.py", line 147, in get
    return recv()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_libs/reads_analyzer.py", line 55, in <module>
    class QuastDeletion(object):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_libs/reads_analyzer.py", line 66, in QuastDeletion
    MIN_GAP = qconfig.extensive_misassembly_threshold - 2 * MAX_CONFIDENCE_INTERVAL
  File "/opt/anaconda3/lib/python3.8/site-packages/joblib/pool.py", line 147, in get
    return recv()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_libs/reads_analyzer.py", line 55, in <module>
    class QuastDeletion(object):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
  File "SQUAST_quality_check_9_Nov_2021/quast-5.1.0rc1/quast_libs/reads_analyzer.py", line 66, in QuastDeletion
    MIN_GAP = qconfig.extensive_misassembly_threshold - 2 * MAX_CONFIDENCE_INTERVAL
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by JosieLikesCats** [comment]
I get the same error. In case it helps: I downloaded quast via conda (channel bioconda). Quast v5.0.2

**Comment by Rajmandage22** [comment]
Hi,

Thanks for the reply. I shall try it with conda.






Raj

On Nov 17, 2021 12:06 PM, Josie ***@***.***> wrote:
External Sender. Be aware of links, attachments and requests.

I get the same error. In case it helps: I downloaded quast via conda (channel bioconda). Quast v5.0.2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fablab%2Fquast%2Fissues%2F191%23issuecomment-971828298&data=04%7C01%7Crmandage%40tulane.edu%7C6853db7ed74840c4685508d9a9f4f9eb%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637727691918713476%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wVBcqMzOIbyqD5vWwTYvpLNnImMgaORnVYEMHFk5zKU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOHQHHQ5IVQ4OS3HVG5SBDUMPVKHANCNFSM5H3H52FQ&data=04%7C01%7Crmandage%40tulane.edu%7C6853db7ed74840c4685508d9a9f4f9eb%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637727691918723449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FwoI4ZJ7StDX%2Btvkn4pYMpJAzHiN6zWy15Wq7dws75Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crmandage%40tulane.edu%7C6853db7ed74840c4685508d9a9f4f9eb%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637727691918723449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E74Z46apM4X7IJMVUDfQZ9pe35EyGPbsfUOuhbIoUzA%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crmandage%40tulane.edu%7C6853db7ed74840c4685508d9a9f4f9eb%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637727691918733394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9EsrU69WHzxQNx9%2F7AtCIJHW5XEnuiCpOf6jVzRGIfc%3D&reserved=0>.

**Comment by JosieLikesCats** [comment]
Just to follow up: once I replaced `extensive_misassembly_threshold = None` with `extensive_misassembly_threshold = <value>` in `quastlibs/qconfig.py` and replaced cgi as described in issue #157 I was able to run the pipeline correctly.

So my follow-up question would be what value/range of values should extensive_misassembly_threshold be replaced by?

**Comment by alexeigurevich** [comment]
Hi, @JosieLikesCats !
Thanks for figuring this out!

As for your question (which you edited out later, but I found it quite useful for future readers)
> So my follow-up question would be what value/range of values should extensive_misassembly_threshold be replaced by?

Our preferred default value is `1000` bp; it was a constant value from the very beginning of QUAST until we added `--extensive-mis-size` option. However, for large genomes, e.g., human genome, we recommend using `3000` bp or an even larger threshold for the sake of speed; please refer to [the QUAST-LG paper](https://pubmed.ncbi.nlm.nih.gov/29949969/).
