### ISSUE TITLE
module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by CAVUling** [ablab/quast#210]
Hi 
the content of log is 
```
module 'cgi' has no attribute 'escape'
Traceback (most recent call last):
  File "/share/home/ZengLT/apps/quast-5.0.2/quast.py", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/share/home/ZengLT/apps/quast-5.0.2/quast.py", line 148, in main
    from quast_libs import basic_stats
  File "/share/home/ZengLT/apps/quast-5.0.2/quast_libs/basic_stats.py", line 15, in <module>
    from quast_libs.circos import set_window_size
  File "/share/home/ZengLT/apps/quast-5.0.2/quast_libs/circos.py", line 25, in <module>
    from quast_libs.icarus_utils import get_assemblies, check_misassembled_blocks, Alignment
  File "/share/home/ZengLT/apps/quast-5.0.2/quast_libs/icarus_utils.py", line 15, in <module>
    from quast_libs.html_saver.html_saver import trim_ref_name
  File "/share/home/ZengLT/apps/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 18, in <module>
    from quast_libs.site_packages.jsontemplate import jsontemplate
  File "/share/home/ZengLT/apps/quast-5.0.2/quast_libs/site_packages/jsontemplate/jsontemplate.py", line 583, in <module>
    'html': cgi.escape,
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by alexeigurevich** [comment]
Sorry for the incovenience. This issue is already discussed (and solved) in https://github.com/ablab/quast/issues/157
