### ISSUE TITLE
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by dagi34** [ablab/quast#211]
[quast_log.docx](https://github.com/ablab/quast/files/8387398/quast_log.docx)

Hi,
Quast terminated before finishing job. I think the most revieling information in the log is the one in the subject line. I attach the whole log for your perusal. Please advice.
I installed via conda and the list of packages seems to be okay.

Thank you

**Comment by some0nenew** [comment]
A year later I get pretty much the exact same error. I'm completely new to the program and cant guarantee that this is not a user error, but at least i cant find any obvious faults on my side.

Installed Quast via pip, checked for dependencies, reinstalled it, tried alternative datasets. Always get this error, only difference is the position and the byte it returns.

[quast.log](https://github.com/ablab/quast/files/11365323/quast.log)

**Comment by emics57** [comment]
Hello, I also have the exact same error as @dagi34. Also installed via conda. Anyone figure out a solution for this?

**Comment by some0nenew** [comment]
@emics57 maybe this works for you, sadly i only have my rather lackluster notes, at least this is better than no reply at all.

My problem was that i used the Software the first time, didn't know how to use it and fed it the wrong file. I supplied a "contigs.seq" file, after some trial and error i figured out that quast wants to get *.fasta files. After i did that everything went fine.

**Comment by vatanparast** [comment]
As of April 2024, I can confirm this issue exists with the QUAST v. 5.2.0. I generated specific conda env, but the issue persists.

```
2024-04-26 09:54:15
Running Reads analyzer...
WARNING: Version of installed minimap2 differs from its version in the QUAST package (2.24). Please make sure that you use an actual version of software.

'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte
Traceback (most recent call last):
  File "miniconda/envs/quast/bin/quast", line 309, in <module>
    return_code = main(sys.argv[1:])
  File "miniconda/envs/quast/bin/quast", line 118, in main
    bed_fpath, cov_fpath, physical_cov_fpath = reads_analyzer.do(ref_fpath, contigs_fpaths,
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/reads_analyzer.py", line 940, in do
    all([paired_reads_names_are_equal([read1, read2], temp_output_dir, logger)
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/reads_analyzer.py", line 940, in <listcomp>
    all([paired_reads_names_are_equal([read1, read2], temp_output_dir, logger)
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/ra_utils/misc.py", line 171, in paired_reads_names_are_equal
    first_line = handler.readline()
  File "miniconda/envs/quast/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte
ERROR! exception caught!
2024-04-26 09:54:15
Running Reads analyzer...
WARNING: Version of installed minimap2 differs from its version in the QUAST package (2.24). Please make sure that you use an actual version of software.

'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte
Traceback (most recent call last):
  File "miniconda/envs/quast/bin/quast", line 309, in <module>
    return_code = main(sys.argv[1:])
  File "miniconda/envs/quast/bin/quast", line 118, in main
    bed_fpath, cov_fpath, physical_cov_fpath = reads_analyzer.do(ref_fpath, contigs_fpaths,
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/reads_analyzer.py", line 940, in do
    all([paired_reads_names_are_equal([read1, read2], temp_output_dir, logger)
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/reads_analyzer.py", line 940, in <listcomp>
    all([paired_reads_names_are_equal([read1, read2], temp_output_dir, logger)
  File "miniconda/envs/quast/opt/quast-5.2.0/quast_libs/ra_utils/misc.py", line 171, in paired_reads_names_are_equal
    first_line = handler.readline()
  File "miniconda/envs/quast/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte
ERROR! exception caught!
```

**Comment by JWDebler** [comment]
Same problem here. Just installed via conda and keep running into this error when providing alignments in bam format.
