### ISSUE TITLE
ERROR! exception caught! in QUAST v5.2.0

### ISSUE THREAD

**Issue by ReneKat** [ablab/quast#216]
Hello wonderful quast developers, 

I am on a Ubuntu 20.04 Linux machine with QUAST v5.2.0 installed.
I'm running metaquast.py on 3 co-assemblies. It looks like it's failing during MetaGeneMark:

...

> All references were combined in combined_reference.fasta
> 
> Starting quast.py for the combined reference...
> (logging to /home/fch/Projects/LG6/02_Assembly/quast/combined_reference/quast.log)
> 
> Error sending result: '[([<quast_libs.genes_parser.Gene object at 0x7f3f4773d990>, <quast_libs.genes_parser.Gene object at 0x7f3f4773db10>, <quast
> _libs.genes_parser.Gene object at 0x7f3f4773da90>, <quast_libs.genes_parser.Gene object at 0x7f3f4773dc10>, ............ <quast_libs.genes_parser.Gene object at 0x7f3c47e9bd90>, <quast_libs.genes_parser.Gene object at 0x7f3c47e9bd50>, <quast_libs.genes_parser.Gene object at 0x7f3c47e9bdd0>], 3445978, [2729804, 2085118, 197989, 17017], [724152, 518380, 19525, 1328])]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647")'
ERROR! exception caught!

Please let me know what other information you need. 
Thanks so much!
Rene

**Comment by ReneKat** [comment]
Hello again,
I went ahead and ran metaquast.py again but this time without the gene-calling -f argument. However, I got a similar exception caught:

> Drawing NGA50 metaQUAST summary plot...
>     saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/PDF/NGA50.pdf
>   Drawing LGA50 metaQUAST summary plot...
>     saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/PDF/LGA50.pdf
> 
>   Text versions of reports and plots for each metric (for all references and assemblies) are saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/
>   Icarus (contig browser) is saved to /home/fch/Projects/LG6/02_Assembly/quast/icarus.html
>   Drawing interactive Krona plots...
> 
> 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/home/fch/miniconda3/envs/quast/bin/metaquast.py", line 427, in <module>
>     return_code = main(sys.argv[1:])
>   File "/home/fch/miniconda3/envs/quast/bin/metaquast.py", line 417, in main
>     html_saver.create_meta_report(output_dirpath, json_texts)
>   File "/home/fch/miniconda3/envs/quast/lib/python3.7/site-packages/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
>     create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
>   File "/home/fch/miniconda3/envs/quast/lib/python3.7/site-packages/quast_libs/html_saver/html_saver.py", line 363, in create_krona_charts
>     for section in report:
> TypeError: 'NoneType' object is not iterable
> ERROR! exception caught!

**Comment by RayanaFeltrin** [comment]
Hello, @ReneKat 
I've also had the same exact error using metaQUAST. Did you find out how to figure it out?
Thank you in advance.

**Comment by rbtoscan** [comment]
> Hello again, I went ahead and ran metaquast.py again but this time without the gene-calling -f argument. However, I got a similar exception caught:
> 
> > Drawing NGA50 metaQUAST summary plot...
> > saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/PDF/NGA50.pdf
> > Drawing LGA50 metaQUAST summary plot...
> > saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/PDF/LGA50.pdf
> > Text versions of reports and plots for each metric (for all references and assemblies) are saved to /home/fch/Projects/LG6/02_Assembly/quast/summary/
> > Icarus (contig browser) is saved to /home/fch/Projects/LG6/02_Assembly/quast/icarus.html
> > Drawing interactive Krona plots...
> > 'NoneType' object is not iterable
> > Traceback (most recent call last):
> > File "/home/fch/miniconda3/envs/quast/bin/metaquast.py", line 427, in 
> > return_code = main(sys.argv[1:])
> > File "/home/fch/miniconda3/envs/quast/bin/metaquast.py", line 417, in main
> > html_saver.create_meta_report(output_dirpath, json_texts)
> > File "/home/fch/miniconda3/envs/quast/lib/python3.7/site-packages/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
> > create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
> > File "/home/fch/miniconda3/envs/quast/lib/python3.7/site-packages/quast_libs/html_saver/html_saver.py", line 363, in create_krona_charts
> > for section in report:
> > TypeError: 'NoneType' object is not iterable
> > ERROR! exception caught!

facing the same issue. has this been addressed?

**Comment by RayanaFeltrin** [comment]
Hey @rbtoscan!
I had a similar problem last year as reported in https://github.com/ablab/quast/issues/251.
The solution was to use the flag `--no-krona` that @alexeigurevich created as a workaround. However, since then they still didn't release a new QUAST version :/

Good luck!

**Comment by rbtoscan** [comment]
nice, thank you very much, @RayanaFeltrin!

will give it a try :)
