### ISSUE TITLE
Metaquast 5.2 summary error

### ISSUE THREAD

**Issue by JianxinS0806** [ablab/quast#237]
When I run quast successfully, the following error occurs in the summarizing result stage

Summarizing results...
  Drawing # contigs metaQUAST summary plot...
    saved to /media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/PDF/num_contigs.pdf
  Drawing Largest contig metaQUAST summary plot...
    saved to /media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/PDF/Largest_contig.pdf
  Drawing Total length metaQUAST summary plot...
    saved to /media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/PDF/Total_length.pdf
  Drawing Largest alignment metaQUAST summary plot...
    saved to /media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/PDF/Largest_alignment.pdf
  Drawing Total aligned length metaQUAST summary plot...
    saved to /media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/PDF/Total_aligned_length.pdf
  Drawing Total length (>= 1000 bp) metaQUAST summary plot...

[Errno 22] Invalid parameter: '/media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/coordTotal_length_(>=_1000_bp).json'
Traceback (most recent call last):
  File "/home/jxs/anaconda3/envs/quast/bin/metaquast", line 427, in <module>
    return_code = main(sys.argv[1:])
  File "/home/jxs/anaconda3/envs/quast/bin/metaquast", line 411, in main
    output_dirpath_per_ref, metrics_for_plots, misassembly_metrics, full_ref_names)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/create_meta_summary.py", line 108, in do
    print_all_refs=True, logger=logger)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/plotter.py", line 685, in draw_meta_summary_plot
    title.replace(' ', '_'), labels, refs_for_html)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/html_saver/html_saver.py", line 451, in save_meta_summary
    json_fpath = json_saver.save_meta_summary(results_dirpath, coord_x, coord_y, name_coord, labels, refs)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/html_saver/json_saver.py", line 169, in save_meta_summary
    'refnames': refs_names
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/html_saver/json_saver.py", line 50, in save
    json_file = open(fpath, 'w')
OSError: [Errno 22] Invalid parameter
: '/media/jxs/Data/metagenomic_data/BN221214NY01S03N1/rawdata/1883-1/megahit_out/metaquast_out/summary/coordTotal_length_(>=_1000_bp).json'
[metaquast.log](https://github.com/ablab/quast/files/10776284/metaquast.log)
This confuses me a lot. And hope to get your help, thanks.

**Comment by asl** [comment]
Hello

It seems your output directory is on some removable storage and the file system there does not allow special symbols in paths (e.g. ">" or "=" like here). I would suggest you to move output directory elsewhere.

**Comment by JianxinS0806** [comment]
Thank you very much for your answer! According to the method you suggested, I have successfully solved the previous problem. Meanwhile another new problem popped up, and I noticed that ReneKat had the same problem(ERROR!exception caught! in QUAST v5.2.0 #216). The specific error is as follows:

  Drawing LGA50 metaQUAST summary plot...
    saved to /home/jxs/metaquast_out/summary/PDF/LGA50.pdf

  Text versions of reports and plots for each metric (for all references and assemblies) are saved to /home/jxs/metaquast_out/summary/
  Icarus (contig browser) is saved to /home/jxs/metaquast_out/icarus.html
  Drawing interactive Krona plots...

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/jxs/anaconda3/envs/quast/bin/metaquast", line 427, in <module>
    return_code = main(sys.argv[1:])
  File "/home/jxs/anaconda3/envs/quast/bin/metaquast", line 417, in main
    html_saver.create_meta_report(output_dirpath, json_texts)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
    create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
  File "/home/jxs/anaconda3/envs/quast/opt/quast-5.2.0/quast_libs/html_saver/html_saver.py", line 363, in create_krona_charts
    for section in report:
TypeError: 'NoneType' object is not iterable
[metaquast_2.log](https://github.com/ablab/quast/files/10778526/metaquast_2.log)
I would be very grateful for any help that you provide.

**Comment by RayanaFeltrin** [comment]
Hello, @JianxinS0806 
I've also had the same exact error using metaQUAST. Did you find out how to figure it out?
Thank you in advance.

**Comment by Rose0498** [comment]
Hi,
I was able to complete the Metaquast analysis, however the HTML report isn't loading 
![image](https://github.com/ablab/quast/assets/171794621/a2b89cc6-f9ae-4a51-a0bb-c3e13059b766)
![image](https://github.com/ablab/quast/assets/171794621/e425a3a3-2c34-4e26-8a87-bad351ddb3b2)

 can anyone help me with the same?
