### ISSUE TITLE
Error while creating Krona plots

### ISSUE THREAD

**Issue by VictorBenedito** [ablab/quast#246]
2023-06-21 12:07:40
Summarizing results...

  Text versions of reports and plots for each metric (for all references and assemblies) are saved to /MP_Data/speedypipe/USER189_PROJECT189/results/M1/metaquast/summary/
  Icarus (contig browser) is saved to /MP_Data/speedypipe/USER189_PROJECT189/results/M1/metaquast/icarus.html
  Drawing interactive Krona plots...

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ocardenas/.local/bin/metaquast.py", line 427, in <module>
    return_code = main(sys.argv[1:])
  File "/home/ocardenas/.local/bin/metaquast.py", line 417, in main
    html_saver.create_meta_report(output_dirpath, json_texts)
  File "/home/ocardenas/.local/lib/python3.9/site-packages/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
    create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
  File "/home/ocardenas/.local/lib/python3.9/site-packages/quast_libs/html_saver/html_saver.py", line 363, in create_krona_charts
    for section in report:
TypeError: 'NoneType' object is not iterable
ERROR! exception caught!

**Comment by RayanaFeltrin** [comment]
Hello, @VictorBenedito 
I've also had the same exact error using metaQUAST. Did you find out how to figure it out?
Thank you in advance.
