### ISSUE TITLE
Error creating Krona plots in metaquast.py

### ISSUE THREAD

**Issue by RayanaFeltrin** [ablab/quast#251]
Hello!

I've recently run the command `metaquast.py -o quast_ANT001 --large -l metaSPAdes,MEGAHIT meta_assembly_001ANT/contigs.fasta mega_assembly_001ANT/final.contigs.fa`

At the final step of the software, I got the following error, which was also obtained in #246 and #237 and still not solved:

_Drawing interactive Krona plots..._

_'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/rayana/Desktop/tools/quast/metaquast.py", line 427, in <module>
    return_code = main(sys.argv[1:])
  File "/home/rayana/Desktop/tools/quast/metaquast.py", line 417, in main
    html_saver.create_meta_report(output_dirpath, json_texts)
  File "/home/rayana/Desktop/tools/quast/quast_libs/html_saver/html_saver.py", line 257, in create_meta_report
    create_krona_charts(taxons_for_krona, meta_log, results_dirpath, json_texts)
  File "/home/rayana/Desktop/tools/quast/quast_libs/html_saver/html_saver.py", line 363, in create_krona_charts
    for section in report:
TypeError: 'NoneType' object is not iterable_

I really need to solve this to continue my work and would appreciate any help.

Thank you in advance.

**Comment by RayanaFeltrin** [comment]
@alexeigurevich @vyahhi @asl @ad3002 @sjackman, help please!l

**Comment by alexeigurevich** [comment]
@RayanaFeltrin sorry for the huge delay, I am looking into this right now!

**Comment by RayanaFeltrin** [comment]
Thank you, @alexeigurevich ! I just runned it with --no-krona and it worked!

**Comment by RayanaFeltrin** [comment]
Hello @alexeigurevich!

I am also facing the same problem as @bheimbu... I've run the following command:
`metaquast.py scaffolds.fasta final.contigs.fa -o quast_ANT001 -t 10 --large --no-krona > quast_ANT001.out 2> quast_ANT001.err`

... and got the error:

_Usage: metaquast.py [options]_

_metaquast.py: error: no such option: --no-krona_

What could I do to solve this?
Thank you in advance!

**Comment by bgruening** [comment]
@alexeigurevich can you please create a new release? I can create a new conda package.

**Comment by LottePronk** [comment]
I'm encountering the same error and I need the conda package to integrate into a pipeline. Any idea when a new release will be coming?

**Comment by bgruening** [comment]
Yes, I can take care of this. Thanks for fixing.

**Comment by bgruening** [comment]
The Conda package and the Containers are up, the Galaxy integrations will come tomorrow.

I saw this here in the logs:

```
Python recognizes 'quast_libs.minimap2.sse2neon' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
 
 This leads to an ambiguous overall configuration. If you want to distribute this
 package, please make sure that 'quast_libs.minimap2.sse2neon' is explicitly added
 to the `packages` configuration field.

Alternatively, you can also rely on setuptools' discovery methods
(for example by using `find_namespace_packages(...)`/`find_namespace:`
instead of `find_packages(...)`/`find:`).

You can read more about "package discovery" on setuptools documentation page:
 - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
```

**Comment by RayanaFeltrin** [comment]
Thank you so much @alexeigurevich @bgruening!

Best
