### ISSUE TITLE
Error occured while running Busco

### ISSUE THREAD

**Issue by jayramr** [ablab/quast#259]
Hi

Kindly advise, we are using conda version of quast 5.0.2 

```

quast -t 28 -f -b -o quast_test -1 ../../R6_read1_trimmomatic_1PE.fastq.gz -2 ../../R6_read2_trimmomatic_2PE.fastq.gz R6_RcB5_frag_pilon.fast

2024-01-29 18:01:54
Running BUSCO...


'BuscoConfig' object has no attribute 'readfp'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/software/joblib/1.2.0/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/software/joblib/1.2.0/lib/python3.12/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/joblib/1.2.0/lib/python3.12/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/run_busco.py", line 130, in busco_main_handler
    return busco.main(*busco_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/busco/busco.py", line 155, in main
    config = BuscoConfig(config_file, args={'in': in_fpath, 'out': out_fname})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/busco/BuscoConfig.py", line 73, in __init__
    super(BuscoConfig, self).__init__(conf_file)
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/busco/pipebricks/PipeConfig.py", line 34, in __init__
    self.readfp(open(self.conf_file), 'r')  # deprecated but kept for 2.7
    ^^^^^^^^^^^
AttributeError: 'BuscoConfig' object has no attribute 'readfp'. Did you mean: 'read'?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/software/quast/5.0.2/bin/quast", line 307, in <module>
    return_code = main(sys.argv[1:])
                  ^^^^^^^^^^^^^^^^^^
  File "/software/quast/5.0.2/bin/quast", line 228, in main
    run_busco.do(contigs_fpaths, os.path.join(output_dirpath, qconfig.busco_dirname), logger)
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/run_busco.py", line 216, in do
    summary_fpaths = run_parallel(busco_main_handler, busco_args, qconfig.max_threads)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/quast/5.0.2/opt/quast-5.0.2/quast_libs/qutils.py", line 1065, in run_parallel
    results_tuples = Parallel(**parallel_args)(delayed(_fn)(*args) for args in fn_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/joblib/1.2.0/lib/python3.12/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/software/joblib/1.2.0/lib/python3.12/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/joblib/1.2.0/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'BuscoConfig' object has no attribute 'readfp'
```

Thanks
Jay

**Comment by jayramr** [comment]
@alexeigurevich  please look into this.

**Comment by mbeavitt** [comment]
Same issue with 5.2.0

**Comment by zhengxinchang** [comment]
same issue with 5.3.0
