### ISSUE TITLE
Error when running "Generating Upper Bound Assembly"

### ISSUE THREAD

**Issue by kkowalden** [ablab/quast#71]
Hello,
The following error is returned when running QUAST-LG with the upper bound assembly option, which then kills the job.

./quast.py -o ./Quast_test/ -t 22 --upper-bound-assembly -r 10_pilon.fasta --no-sv --no-read-stats --nanopore Reads.fasta.gz --large 1_pilon.fasta

......

2018-09-21 13:47:23
Generating Upper Bound Assembly...
  Pre-processing reads...
  Running BWA for reference...
  Done.
  Sorting SAM-file for reference...
  Calculating reads coverage...
  Running repeat masking tool...

'>=' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/home/apps/software/quast/5.0.0-IGB-gcc-4.9.4-Python-3.6.1/lib/python3.6/site-packages/quast-5.0.0-py3.6.egg/EGG-INFO/scripts/quast.py", line 304, in <module>
    return_code = main(sys.argv[1:])
  File "/home/apps/software/quast/5.0.0-IGB-gcc-4.9.4-Python-3.6.1/lib/python3.6/site-packages/quast-5.0.0-py3.6.egg/EGG-INFO/scripts/quast.py", line 95, in main
    os.path.join(output_dirpath, qconfig.optimal_assembly_basename))
  File "/home/apps/software/quast/5.0.0-IGB-gcc-4.9.4-Python-3.6.1/lib/python3.6/site-packages/quast-5.0.0-py3.6.egg/quast_libs/optimal_assembly.py", line 476, in do
    unique_covered_regions, repeats_regions = get_unique_covered_regions(ref_fpath, tmp_dir, log_fpath, binary_fpath, insert_size, uncovered_fpath, use_long_reads=long_reads)
  File "/home/apps/software/quast/5.0.0-IGB-gcc-4.9.4-Python-3.6.1/lib/python3.6/site-packages/quast-5.0.0-py3.6.egg/quast_libs/optimal_assembly.py", line 379, in get_unique_covered_regions
    if repeat_len >= insert_size:
TypeError: '>=' not supported between instances of 'int' and 'str'
ERROR! exception caught!

Thanks,
Kim

**Comment by alexeigurevich** [comment]
Hi Kim,
It is our bug and I've just fixed it. Thanks for reporting!

The bug occurs when no paired-end reads are specified (the default value for such case is 'auto' and Python3 rightly fails to compare it with an integer number). There is a workaround for this case: please add `--est-insert-size 100` to your running command and everything should be fine. Note that any number between 63 and 1023 will work, we will not use it anyway since only nanopore reads are specified.

**Comment by kkowalden** [comment]
Great, thanks, that solved the issue!
