### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by nick-youngblut** [ablab/quast#78]
I'm running quast 5.0.1 (bioconda; py36pl526ha92aebf_0), and I'm getting the following error:

```
'list' object has no attribute 'split'
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/bin/metaquast", line 406, in <module>
    return_code = main(sys.argv[1:])
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/bin/metaquast", line 323, in main
    run_parallel(_run_quast_per_ref, parallel_run_args, qconfig.max_threads, filter_results=True)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/opt/quast-5.0.1/quast_libs/qutils.py", line 1063, in run_parallel
    results_tuples = Parallel(**parallel_args)(delayed(_fn)(*args) for args in fn_args)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/site-packages/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/bin/metaquast", line 100, in _run_quast_per_ref
    is_parallel_run=is_parallel_run)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/bin/metaquast", line 72, in _start_quast_main
    return_code = quast.main(args)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/opt/quast-5.0.1/quast.py", line 56, in main
    quast_py_args, contigs_fpaths = parse_options(logger, quast_path + args)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/opt/quast-5.0.1/quast_libs/options_parser.py", line 833, in parse_options
    qconfig.labels = qutils.parse_labels(qconfig.labels, contigs_fpaths)
  File "/ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast/opt/quast-5.0.1/quast_libs/qutils.py", line 374, in parse_labels
    labels = remove_quotes(line).split(',')
AttributeError: 'list' object has no attribute 'split'
```

I'm running metaquast with the following parameters:

```
metaquast --gene-finding  -R /PATH/TO/REF_FILES/ref_genomes -o /OUTPUT/PATH/metaquast -t 30 /INPUT/PATH/athena.asm.fa
```

My conda env is:

```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blast                     2.5.0                hc0b0e79_3    bioconda
boost                     1.68.0           py36h3e44d54_1    conda-forge
boost-cpp                 1.68.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
circos                    0.69.6                        2    bioconda
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
glimmerhmm                3.0.4                h2d50403_2    bioconda
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.0                      118
joblib                    0.13.0                     py_0    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgd                     2.2.5                hed1f559_4    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libwebp                   1.0.0                he252da6_1    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
matplotlib                2.2.3            py36h8e2386c_0    conda-forge
mkl                       2019.0                      118
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.15.0           py36h1b885b7_0
numpy-base                1.15.0           py36h3dfced4_0
openjdk                   8.0.152              h46b5887_1
openssl                   1.0.2p               h470a237_1    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
perl-autoloader           5.74                    pl526_1    bioconda
perl-carp                 1.38                    pl526_1    bioconda
perl-clone                0.41            pl526h470a237_0    bioconda
perl-config-general       2.61                    pl526_1    bioconda
perl-data-dumper          2.161                   pl526_2    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.000000                pl526_0    bioconda
perl-extutils-makemaker   7.34                    pl526_2    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.69            pl526he941832_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-math-bezier          0.01                    pl526_1    bioconda
perl-math-round           0.07                    pl526_1    bioconda
perl-math-vecstat         0.08                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_0    bioconda
perl-number-format        1.75                    pl526_3    bioconda
perl-params-validate      1.29            pl526h470a237_0    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.73                 h470a237_2    bioconda
perl-readonly             1.04                    pl526_2    bioconda
perl-regexp-common        2017060201              pl526_0    bioconda
perl-scalar-list-utils    1.45            pl526h470a237_3    bioconda
perl-set-intspan          1.19                    pl526_1    bioconda
perl-statistics-basic     1.6611                  pl526_2    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-test-more            1.001002                pl526_1    bioconda
perl-text-format          0.59                    pl526_1    bioconda
perl-time-hires           1.9758                  pl526_0    bioconda
perl-try-tiny             0.30                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526h3a4f0e9_1    conda-forge
perl-xsloader             0.24                    pl526_0    bioconda
pip                       18.1                  py36_1000    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
python                    3.6.6                h5001a0f_3    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
quast                     5.0.1           py36pl526ha92aebf_0    bioconda
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
simplejson                3.16.1           py36h470a237_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

conda info:

```
     active environment : quast
    active env location : /ebio/abt3_projects/software/miniconda3_gt4.4/envs/quast
            shell level : 1
       user config file : /ebio/abt3/nyoungblut/.condarc
 populated config files : /ebio/abt3_projects/software/miniconda3_gt4.4/.condarc
                          /ebio/abt3/nyoungblut/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /ebio/abt3_projects/software/miniconda3_gt4.4  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/leylabmpi/linux-64
                          https://conda.anaconda.org/leylabmpi/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
          package cache : /ebio/abt3_projects/software/miniconda3_gt4.4/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
       envs directories : /ebio/abt3_projects/software/miniconda3_gt4.4/envs
                          /ebio/abt3/nyoungblut/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/4.9.127 ubuntu/18.04 glibc/2.27
                UID:GID : 6354:350
             netrc file : None
           offline mode : False
```

**Comment by alexeigurevich** [comment]
I suppose it could be due to `joblib v.0.13`, they slightly changed the behavior since `v.0.12` (on which we tested `5.0.1`). We have a fix for that and plan to deploy 5.0.2 next week (including `bioconda` update).
However, I will anyway check that the `joblib` is the real source of your problem (a little bit later). Or you can try to downgrade to `joblib 0.12` or earlier and restart.

**Comment by nick-youngblut** [comment]
I'm still getting the same error with joblib 0.12.5 (conda-forge; py_0). Do you know which v0.12 would work?

**Comment by alexeigurevich** [comment]
We checked the issue and it is indeed due to the newest `joblib` versions (and occurs only in MetaQUAST with a single assembly -- It was difficult to catch the bug during the testing). We tested now that everything works correctly with `joblib 0.9.2`(this version is provided in the standalone Quast package). So, you can downgrade to `0.9.2` to make it work.

Anyway, the fix is already [committed](https://github.com/ablab/quast/commit/593432ee745d33e62de5d4f82202f4b0975e305f) and we plan to release `QUAST v.5.0.2` early this week (including the `bioconda` release).
