### ISSUE TITLE
error running post install after quast update to 5.0.2

### ISSUE THREAD

**Issue by splaisan** [ablab/quast#80]
Hi,

The 5.0.2 installer finished with proposing to install additional tools, I tried the provided commands and they all fail as below.

What should I install to get the plugins?

Thanks
Stephane

```
conda install -c bioconda quast=5.0.2
...
...
- The default QUAST package does not include:
* GRIDSS (needed for structural variants detection)
* SILVA 16S rRNA database (needed for reference genome detection in metagenomic datasets)
* BUSCO tools and databases (needed for searching BUSCO genes) -- works in Linux only!

To be able to use those, please run
    quast-download-gridss
    quast-download-silva
    quast-download-busco

done

# tried
$ quast-download-gridss
Traceback (most recent call last):
  File "/opt/biotools/miniconda2/envs/atwork3/bin/quast-download-gridss", line 3, in <module>
    from quast_libs import qconfig
ImportError: No module named quast_libs
$ quast-download-silva
Traceback (most recent call last):
  File "/opt/biotools/miniconda2/envs/atwork3/bin/quast-download-silva", line 3, in <module>
    from quast_libs import qconfig
ImportError: No module named quast_libs
$ quast-download-busco
Traceback (most recent call last):
  File "/opt/biotools/miniconda2/envs/atwork3/bin/quast-download-busco", line 3, in <module>
    from quast_libs import qconfig
ImportError: No module named quast_libs
```

**Comment by splaisan** [comment]
Thanks Alexei :-)
