### ISSUE TITLE
Add support for wheels

### ISSUE THREAD

**Issue by vellamike** [ablab/quast#99]
When running `pip install quast` I get the following error:
```
  ERROR: Complete output from command /home/mike/virtualenvs/quastest/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nv0esrne/quast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7eg2xawh --python-tag cp36:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-nv0esrne/quast/setup.py", line 55, in <module>
      raise RuntimeError("This setup.py does not support wheels. setup.py install will be run automatically...")
  RuntimeError: This setup.py does not support wheels. setup.py install will be run automatically...
  ----------------------------------------
  ERROR: Failed building wheel for quast
```

quast does proceed to install but takes a long time which causes a problem on the CI system I am using. Could wheels support be added?

**Comment by Zethson** [comment]
I encountered the same error. Is there any update?

**Comment by alexeigurevich** [comment]
Sorry for the late response and thanks for raising this issue.

When wheels were introduced in Python, we tried to support them in Quast's `setup.py` but failed since its core dependency, `setuptools`, did not support wheels at that time. The newest versions of `setuptools` seem to work fine with wheels, so we will add support for wheels in the next Quast release. We tested that everything is working properly now but can't simply update Quast package on PyPI, a new version should be released (5.0.3 or 5.1.0). I will keep the issue open until then.

Few more comments/suggestions:
For @Zethson 
> I encountered the same error. Is there any update?

Note that this message is not a fatal error, it is mostly a warning after which the installation process continues (and hopefully finishes correctly in the majority of cases). 

For @vellamike 
> quast does proceed to install but takes a long time which causes a problem on the CI system I am using. 

Not sure whether it is feasible for your setting but you can try to get a faster installation using [bioconda](https://anaconda.org/bioconda/quast) which has precompiled Quast versions.

**Comment by suvash** [comment]
Looking forward to this (wheels support) being released.

**Comment by kislyuk** [comment]
Hello, is there any update on this? Wheel support on Python is ubiquitous now, and it would be ideal if Quast could provide pre-built Linux amd64 wheels on PyPI.
